platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MultiCircleImageView_Example', :exclusive => true do
  pod "MultiCircleImageView", :path => "../"
  pod 'SDWebImage'
end

target 'MultiCircleImageView_Tests', :exclusive => true do
  pod "MultiCircleImageView", :path => "../"

    #pod 'Quick', '~> 0.3.1'
  #pod 'Nimble'
end
