platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MultiCircleImageView_Example' do
  pod "MultiCircleImageView", :path => "../"
  pod 'SDWebImage'
end

target 'MultiCircleImageView_Tests' do
  pod "MultiCircleImageView", :path => "../"

end
